version: '2'
services:
    jhipstersamplegateway-sonar:
        container_name: jhipstersamplegateway-sonar
        image: sonarqube:6.0-alpine
        ports:
            - 9000:9000
            - 9092:9092
